---
# tasks file for users

- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install required software
  ansible.builtin.package:
    name: "{{ users_requirements }}"
    state: present

- name: Loop over users_group_list
  ansible.builtin.include_tasks:
    file: group.yml
  loop: "{{ users_group_list }}"
  loop_control:
    label: "{{ group.name }}"
    loop_var: group
  when:
    - users_group_list is defined

- name: Loop over users_user_list
  ansible.builtin.include_tasks:
    file: user.yml
  loop: "{{ users_user_list }}"
  loop_control:
    label: "{{ user.name }}"
    loop_var: user
  when:
    - users_user_list is defined
