---

- name: user | Manage users {{ user.name }}
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: "{{ user.state | default('present') }}"
    comment: "{{ user.comment | default(omit) }}"
    create_home: "{{ users_create_home }}"
    password: "{{ user.password | default(omit) }}"
    uid: "{{ user.uid | default(omit) }}"
    group: "{{ user.group | default(omit) }}"
    groups: "{{ user.groups | default(omit) }}"
    home: "{{ user.home | default(omit) }}"
    shell: "{{ user.shell | default(users_shell) }}"
    update_password: "{{ user.update_password | default(omit) }}"
    expires: "{{ user.expires | default(omit) }}"
    system: "{{ user.system | default(omit) }}"
  register: users_manage_user

- name: user | Set sudo options for {{ user.name }}
  ansible.builtin.template:
    src: sudo.j2
    dest: '/etc/sudoers.d/{{ user.name | replace(".", "dot") }}'
    mode: "0640"
    validate: /usr/sbin/visudo -cf %s
  when:
    - user.sudo_options is defined
  loop_control:
    label: "{{ user.name }}"

- name: user | Remove sudo options for {{ user.name }}
  ansible.builtin.file:
    path: '/etc/sudoers.d/{{ user.name | replace(".", "dot") }}'
    state: absent
  when:
    - user.sudo_options is not defined
  loop_control:
    label: "{{ user.name }}"

- name: user | Ensure the sudoers.d directory is checked for user sudoers files (will be put after EOF if not exists)
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "@includedir /etc/sudoers.d"

- name: user | Get or set the home directory
  block:
    - name: user | Get system users data
      ansible.builtin.getent:
        database: passwd
        key: "{{ user.name }}"
        split: ":"
  rescue:
    - name: user | User not found, that's okay
      ansible.builtin.debug:
        msg: "No user found, that is okay."
  always:
    - name: user | Set home directory to {{ getent_passwd[user.name][4] | default('/home') }}
      ansible.builtin.set_fact:
        users_home_base_dir: "{{ getent_passwd[user.name][4] | default('/home') }}"

- name: user | Create .ssh directory for {{ user.name }}
  ansible.builtin.file:
    path: "{{ users_home_base_dir }}/{{ user.name }}/.ssh"
    state: directory
    mode: "0700"
  become: yes
  become_user: "{{ user.name }}"
  when:
    - (user.manage_ssh_key is defined and user.manage_ssh_key)
      or user.private_keys is defined

- name: user | Deploy authorized keys for {{ user.name }}
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ item }}"
  loop: "{{ user.authorized_keys }}"
  loop_control:
    label: "{{ user.name }}"
  when:
    - user.authorized_keys is defined

- name: user | Remove unauthorized keys for {{ user.name }}
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: absent
    key: "{{ item }}"
  loop: "{{ user.unauthorized_keys }}"
  loop_control:
    label: "{{ user.name }}"
  when:
    - user.unauthorized_keys is defined

- name: user | Check users password valid time
  ansible.builtin.command:
    cmd: 'awk ''BEGIN { FS = ":" } $1 == "{{ user.name }}" { print $5 }'' /etc/shadow'
  register: users_pw_valid
  changed_when: no
  check_mode: no
  when:
    - user.state is defined and user.state != "absent" or
      user.state is not defined

- name: user | Set users password valid time
  ansible.builtin.command:
    cmd: chage -M "{{ user.password_validity_days }}" "{{ user.name }}"
  when:
    - user.password_validity_days is defined
    - users_pw_valid.stdout is defined
    - users_pw_valid.stdout | int !=  user.password_validity_days | int
  changed_when: yes
